mysql:
  build: './mysql'
  environment:
    - MYSQL_ROOT_PASSWORD=rootroot
workbench:
  build: './workbench'
  links:
    - mysql
  ports:
    - "8080:8080"
  environment:
    - JAVA_OPTS=-Xms256m -Xmx512m -Djava.net.preferIPv4Stack=true
kieserver:
  build: './kieserver'
  links:
    - workbench:kie_wb
    - mysql
  ports:
    - "8081:8080"
  environment:
    - JAVA_OPTS=-Xms256m -Xmx512m -Djava.net.preferIPv4Stack=true
